'use strict';

const products = [
  {id:'petal-study',name:'Petal Study No. 01',category:'signature',categoryLabel:'Signature',description:'A sculptural study in blush, cream, and the softest green.',price:3680,availability:'Available',featured:true,image:'https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=900&q=80',alt:'Blush and cream flowers arranged as a sculptural bouquet',composition:'Garden roses · lisianthus · seasonal foliage',care:'Refresh water every 2 days'},
  {id:'quiet-garden',name:'Quiet Garden',category:'seasonal',categoryLabel:'Seasonal',description:'Fresh-cut stems with a little wildness around the edges.',price:2950,availability:'Available',featured:true,image:'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=900&q=80',alt:'A loose seasonal garden flower arrangement',composition:'Seasonal stems · spray roses · airy foliage',care:'Keep cool and away from direct sun'},
  {id:'blush-chapter',name:'The Blush Chapter',category:'signature',categoryLabel:'Signature',description:'Romantic layers of rose, peony, and soft texture.',price:4450,availability:'Limited',featured:true,image:'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=900&q=80',alt:'Layered blush pink flowers in a refined arrangement',composition:'Blush roses · peonies · spray carnations',care:'Trim stems and mist petals lightly'},
  {id:'blue-hour',name:'Blue Hour',category:'seasonal',categoryLabel:'Seasonal',description:'Powder blue accents for a moment that feels unhurried.',price:3890,availability:'Available',featured:false,image:'https://images.unsplash.com/photo-1487070183336-b863922373d4?auto=format&fit=crop&w=900&q=80',alt:'Powder blue and pink flowers in a modern bouquet',composition:'Delphinium · roses · eucalyptus',care:'Change water every other day'},
  {id:'ever-after',name:'Ever After',category:'dried',categoryLabel:'Dried & preserved',description:'A lasting arrangement in warm oat, rust, and faded rose.',price:4150,availability:'Available',featured:false,image:'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=80',alt:'Dried flowers in warm natural and faded rose tones',composition:'Dried lagurus · palm · preserved rose',care:'Keep dry and dust gently with a soft brush'},
  {id:'softly-said',name:'Softly Said',category:'signature',categoryLabel:'Signature',description:'An intimate little bouquet with a generous heart.',price:2590,availability:'Available',featured:false,image:'https://images.unsplash.com/photo-1487530811176-3780de880c2d?auto=format&fit=crop&w=900&q=80',alt:'Small intimate pastel bouquet in a soft palette',composition:'Lisianthus · ranunculus · chamomile',care:'Place in filtered light'},
  {id:'garden-letter',name:'Garden Letter',category:'seasonal',categoryLabel:'Seasonal',description:'A handwritten note from the garden, tied with linen.',price:3490,availability:'Limited',featured:false,image:'https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=900&q=80',alt:'Seasonal garden arrangement tied with natural ribbon',composition:'Seasonal blooms · cosmos · olive leaf',care:'Keep stems submerged and cool'},
  {id:'still-life',name:'Still Life',category:'dried',categoryLabel:'Dried & preserved',description:'Textural, tonal, and made to quietly stay awhile.',price:3150,availability:'Available',featured:false,image:'https://images.unsplash.com/photo-1507501336603-6e31db2be093?auto=format&fit=crop&w=900&q=80',alt:'Textural preserved flower arrangement in muted colors',composition:'Dried hydrangea · bunny tails · ruscus',care:'Avoid moisture and direct sunlight'}
];
